# Numpy

# Aula-05-08-Abril-2021-Numpy-Turma-NOITE-2021

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [4]:
#!pip install numpy

In [5]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [6]:
v1 = np.array( [ 1, 4, 5, 3, 9  ]  )
v1

array([1, 4, 5, 3, 9])

In [7]:
type(v1)

numpy.ndarray

In [8]:
l = [ 9, -3, 5, 6]
l

[9, -3, 5, 6]

In [9]:
type(l)

list

In [10]:
a = np.array(l)
a

array([ 9, -3,  5,  6])

In [11]:
type(a)

numpy.ndarray

In [12]:
a[0] = 4
a

array([ 4, -3,  5,  6])

In [13]:
a.shape

(4,)

In [14]:
len(a)

4

# Funções

In [15]:
range(10)

range(0, 10)

In [16]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
v2 = np.arange(0., 4.5, 0.5) # inicio, fim (Exclusive), passo
v2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [20]:
type(v2)

numpy.ndarray

In [21]:
v2.dtype

dtype('float64')

In [22]:
x = np.arange(1,10, 0.25)
x

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [23]:
x.shape

(36,)

In [24]:
len(x)

36

In [25]:
k = np.zeros(10)
k

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
b = np.array( [True, 10, 'UEPB'] )
b

array(['True', '10', 'UEPB'], dtype='<U21')

# Matrizes

In [27]:
m = np.array( [ [1, 2, 3], [4, 5, 6]    ]  )
m

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
m[0]

array([1, 2, 3])

In [29]:
m[0][0]

1

In [30]:
m.shape

(2, 3)

In [31]:
numero_linhas = m.shape[0]
numero_linhas

2

In [32]:
numero_colunas = m.shape[1]
numero_colunas

3

In [33]:
m.size

6

In [34]:
m.dtype

dtype('int64')

In [35]:
z = np.array( [1, 5, 10], dtype = np.float16  )
z

array([ 1.,  5., 10.], dtype=float16)

# Método random()