# Aula-01-Setembro-2020-Numpy-Noite

# Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [5]:
v1 = np.array( [0, 2, 3, 4, 7, 8, 10])
v1

array([ 0,  2,  3,  4,  7,  8, 10])

In [6]:
type(v1)

numpy.ndarray

In [7]:
l = [ 3, -1, -2, 56, 2 , 9, 10]
l

[3, -1, -2, 56, 2, 9, 10]

In [8]:
type(l)

list

In [9]:
a = np.array(l)
a

array([ 3, -1, -2, 56,  2,  9, 10])

In [10]:
type(a)

numpy.ndarray

In [11]:
a[0] = 100
a

array([100,  -1,  -2,  56,   2,   9,  10])

In [12]:
a[0] = 'cct'

ValueError: invalid literal for int() with base 10: 'cct'

In [13]:
a.shape

(7,)

## Funções 

In [14]:
#              Inicio, Fim (exclusive), passo ou incremento
v2 = np.arange(0., 4.5, .5)
v2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
type(v2)

In [ ]:
v2.dtype

In [ ]:
x = np.arange(1, 10, 0.25)
x

In [ ]:
x = np.zeros(10)
x

In [ ]:
x.shape

In [ ]:
b = np.array([True, False, False, True])
b

In [ ]:
type(b)

In [ ]:
b.dtype

In [ ]:
s = np.array(['python', 'kéras', 'tensorflow'])
s

## Matrizes

In [ ]:
m1 = np.array([ [1,2,3], [4,5,6]  ])
m1

In [ ]:
m1[1][2]

In [ ]:
m1.shape

In [ ]:
num_linhas = m1.shape[0]
num_linhas

In [ ]:
num_colunas = m1.shape[1]
num_colunas

In [ ]:
m1.size # numero de elementos

In [ ]:
m1.dtype

In [ ]:
x = np.array([1, 2])
x.dtype

In [ ]:
y = np.array([1.0, 2.0])
y.dtype

In [ ]:
z = np.array([1, 2], dtype=np.float16)
z.dtype

In [ ]:
z

## Método random()

In [ ]:
np.set_printoptions(suppress=True)
np.random.rand(10)

In [ ]:
np.set_printoptions(suppress=True, precision=5)
np.random.rand(10)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.show( plt.hist(np.random.rand(100)))

In [ ]:
plt.show( plt.hist(np.random.rand(20000)))

In [ ]:
plt.show( plt.hist(np.random.randn(1000)))

In [ ]:
plt.show( plt.hist(np.random.randn(10000)))

In [ ]:
url = 'https://raw.githubusercontent.com/vladimiralencar/Alunos-UEPB-TopicosEspeciaisEmBancoDeDados/master/Python-Para-Analise-de-Dados/iris.csv'

In [ ]:
arq = np.loadtxt(url, delimiter=',', usecols=(0,1,2,3), skiprows=1)
arq

In [ ]:
arq.dtype

In [ ]:
type(arq)

In [ ]:
arq.shape

In [ ]:
d1, d2 = np.loadtxt(url, delimiter=',', usecols=(0,1), skiprows=1, unpack=True)

In [ ]:
d1[:10]

In [ ]:
plt.show( plt.hist(d1))

In [ ]:
plt.show( plt.hist(d2))

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.show(plt.plot(d1,d2, 'o', markersize=8, alpha=0.75))

# Estatística - Funções

In [ ]:
a = np.array([1,5,7,9,0,-4,7,8,10, 50, 30])
a

In [ ]:
a.shape

In [ ]:
a.dtype

In [ ]:
media = np.mean(a)
media

In [ ]:
desvio_padrao = np.std(a)
desvio_padrao

In [ ]:
plt.show(plt.hist(a))

In [ ]:
variancia = np.var(a)
variancia

In [ ]:
d = np.arange(1,10) # exclusive 
d

In [ ]:
np.sum(d)

In [ ]:
np.prod(d)

In [ ]:
np.cumsum(d)

In [ ]:
# array com 2 colunas - Distribuição Normal
a = np.random.randn(400, 2)
a.shape

In [ ]:
a[:2]

In [ ]:
col0 = a[:, 0]
col0.shape

In [ ]:
col00 = a[0:400, 0]
col00.shape

In [ ]:
m0 = np.mean(col0)
m0

In [ ]:
a[:3]

In [ ]:
col1 = a[:, 1]
col1.shape

In [ ]:
m1 = np.mean(col1)
m1

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.figure(figsize=(12,8))
plt.plot(col0, col1, 'o', markersize=8, alpha=0.75)
plt.show()

In [ ]:
plt.figure(figsize=(12,8))

plt.plot(m0, m1, 'ro', markersize=16)
plt.plot(col0, col1, 'o', markersize=8, alpha=0.75)
plt.show()

In [ ]:
plt.show(plt.hist(col0))

In [ ]:
plt.show(plt.hist(col1))

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
a[:3]

In [ ]:
np.array([-0.26805,  0.22921, 0.72325, -1.16817])

In [ ]:
np.array([-0.26805,  0.22921, 0.72325, -1.16817]) + 100

In [ ]:
(np.array([-0.26805,  0.22921, 0.72325, -1.16817]) - a.mean()) / a.std()

In [ ]:
np.around([-0.26805,  0.22921, 0.72325, -1.16817])

In [ ]:
c = np.array([-0.26805,  0.22921, 0.72325, -1.16817])
c

In [ ]:
d = c.flatten() # 1 dimensão
d

In [ ]:
# Concatenação de Arrays
w = np.array([5,6])
w

In [ ]:
v = np.array([1,2,3,4])
v

In [ ]:
z = np.concatenate((v,w), axis=0)
z

In [ ]:
# Reshape
a = np.arange(12)
a

In [ ]:
a.shape

In [ ]:
b = a.reshape(3,4)
b

In [ ]:
b = a.reshape(6,2)
b

In [ ]:
b.shape

In [ ]:
b.ndim

In [ ]:
a.ndim