# Aula-05-19-Agosto-2021-Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

In [3]:
v1 = np.array( [0, 1, 3, 4, 5, 6, 7, 8] )
v1

array([0, 1, 3, 4, 5, 6, 7, 8])

In [4]:
type(v1)

numpy.ndarray

In [5]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
a = np.array(l)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(a)

numpy.ndarray

In [9]:
a[0]

0

In [10]:
a[0] = 45
a

array([45,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [11]:
a[0] = 's'
a

ValueError: invalid literal for int() with base 10: 's'

In [ ]:
a.shape

# Funções Numpy

In [ ]:
v2 = np.arange(0., 4.5, .5) # inicio, fim, passo ou incremento
v2

In [ ]:
type(v2)

In [ ]:
v2.dtype

In [ ]:
a = np.zeros(10)
a

In [ ]:
np.eye(3)

In [ ]:
b = np.array( [True, 1, 'uepb', 1.2 ] )
b

In [ ]:
type(b)

# Matrizes

In [ ]:
m = np.array( 
    [ [1, 2, 3],
    [4, 5, 6] ]
)
m

In [ ]:
m[0]

In [ ]:
m[0][2]

In [ ]:
m

In [ ]:
m.shape

In [ ]:
lin = m.shape[0]
col = m.shape[1]
lin, col 

In [ ]:
m.size

In [ ]:
m.dtype

In [ ]:
z = np.array( [1, 5, 8, 4.5], dtype=np.float16 )
z

# Método Random()

In [ ]:
a = np.random.rand(10)
a

In [ ]:
import matplotlib.pyplot as plt


plt.show( plt.hist(a))

In [ ]:
a = np.random.rand(100)
a[:10]

In [ ]:
plt.show( plt.hist(a))

In [ ]:
a = np.random.rand(10000)
a[:10]

In [ ]:
plt.show( plt.hist(a))

# Distribução Normal

In [ ]:
n = np.random.randn( 100 )
plt.show( plt.hist(n))

In [ ]:
n = np.random.randn( 1000 )
plt.show( plt.hist(n))

In [ ]:
n = np.random.randn( 10000 )
plt.show( plt.hist(n))

# Leitura de arquivo

In [ ]:
url = 'https://raw.githubusercontent.com/vladimiralencar/Alunos-UEPB-TopicosEspeciaisEmBancoDeDados/master/Python-Para-Analise-de-Dados/iris.csv'
url

In [ ]:
m = np.loadtxt(url, delimiter=',', usecols=(0,1,2,3), skiprows=1)
m

In [ ]:
m.shape

In [ ]:
m.dtype

In [ ]:
a1, a2 = np.loadtxt(url, delimiter=',', usecols=(0,1), skiprows=1, unpack=True)
a1

In [ ]:
a2

In [ ]:
plt.show( plt.plot(a1, a2, 'o', markersize=8, alpha=0.75))

# Estatística - Funções

In [ ]:
a = np.array( [12, 3, 4, 7, 5, 1, 4, 11] )
a

In [ ]:
a.shape

In [ ]:
a.dtype

In [ ]:
media = np.mean(a)
media

In [ ]:
a1

In [ ]:
a1.shape

In [ ]:
plt.show( plt.hist(a1))

In [ ]:
a1.min()

In [ ]:
a1.max()

In [ ]:
a1.mean()

In [ ]:
a1.std()

In [ ]:
5.8 - 0.8

In [ ]:
5.8+0.8

In [ ]:
a1.var()

In [ ]:
###

In [ ]:
d = np.arange(1,10)
d

In [ ]:
np.sum(d)

In [ ]:
np.prod(d)

In [ ]:
np.cumsum(d)

In [ ]:
a = np.random.randn(400, 2)
a.shape

In [ ]:
m1 = np.mean(a)
m1

In [ ]:
np.std(a)

# Colocar em Escala (Normalização - Média = 0, Desvio Padrao = 1)

In [ ]:
a = np.random.randn(1000)
a[:15]

In [ ]:
plt.show( plt.hist( a ))

In [ ]:
a.std()

In [ ]:
a.std() * 3

In [ ]:
a.std() * - 3

In [ ]:
a = np.random.rand(1000)
a[:10]

In [ ]:
plt.show( plt.hist(a) )

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
# Colocar em escala

In [ ]:
a_scaled = (a - a.mean()) / a.std()
a_scaled[:10]

In [ ]:
plt.show( plt.hist(a_scaled) )

In [ ]:
# Peso - 20 a 200 kg
# altura - 140 a 2.30

In [ ]:
# mudar o formato (shape)

In [ ]:
c = np.array([ [2,3,4], [5,6,7] ])
c

In [ ]:
c.shape

In [ ]:
d = c.reshape(3,2)
d

In [ ]:
d.shape

In [ ]:
d.ndim