# Aula-01-Setembro-2020-Numpy-Noite

# Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [4]:
v1 = np.array( [0, 2, 3, 4, 7, 8, 10])
v1

array([ 0,  2,  3,  4,  7,  8, 10])

In [5]:
type(v1)

numpy.ndarray

In [6]:
l = [ 3, -1, -2, 56, 2 , 9, 10]
l

[3, -1, -2, 56, 2, 9, 10]

In [7]:
type(l)

list

In [8]:
a = np.array(l)
a

array([ 3, -1, -2, 56,  2,  9, 10])

In [9]:
type(a)

numpy.ndarray

In [10]:
a[0] = 100
a

array([100,  -1,  -2,  56,   2,   9,  10])

In [11]:
#a[0] = 'cct'

ValueError: invalid literal for int() with base 10: 'cct'

In [12]:
a.shape

(7,)

## Funções 

In [13]:
#              Inicio, Fim (exclusive), passo ou incremento
v2 = np.arange(0., 4.5, .5)
v2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [14]:
type(v2)

numpy.ndarray

In [15]:
v2.dtype

dtype('float64')

In [16]:
x = np.arange(1, 10, 0.25)
x

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [17]:
x.shape

(36,)

In [18]:
len(x)

36

In [19]:
k = np.zeros(10)
k

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
k.shape

(10,)

In [21]:
b = np.array([True, False, False, True])
b

array([ True, False, False,  True])

In [22]:
type(b)

numpy.ndarray

In [23]:
b.dtype

dtype('bool')

In [24]:
s = np.array(['python', 'kéras', 'tensorflow'])
s

array(['python', 'kéras', 'tensorflow'], dtype='<U10')

In [25]:
t = np.array(['python', 10, 'tensorflow'])
t

array(['python', '10', 'tensorflow'], dtype='<U10')

## Matrizes

In [26]:
m1 = np.array([ [1,2,3], [4,5,6]  ])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
m1[1][2]

6

In [28]:
m1.shape

(2, 3)

In [29]:
num_linhas = m1.shape[0]
num_linhas

2

In [30]:
num_colunas = m1.shape[1]
num_colunas

3

In [31]:
m1.size # numero de elementos

6

In [32]:
m1.dtype

dtype('int64')

In [33]:
x = np.array([1, 2])
x.dtype

dtype('int64')

In [34]:
y = np.array([1.0, 2.0])
y.dtype

dtype('float64')

In [35]:
z = np.array([1, 2], dtype=np.float16)
z.dtype

dtype('float16')

In [36]:
z

array([1., 2.], dtype=float16)

## Método random()

In [39]:
np.random.rand(10)

array([0.32518445, 0.61579357, 0.91216839, 0.24722958, 0.90744519,
       0.77998824, 0.55724174, 0.67903685, 0.09615374, 0.15882775])

In [40]:
np.set_printoptions(suppress=True)
np.random.rand(10)

array([0.70025598, 0.94883939, 0.81001062, 0.47732529, 0.57104936,
       0.9197429 , 0.74695133, 0.99376887, 0.22134977, 0.42120445])

In [ ]:
np.set_printoptions(suppress=True, precision=5)
np.random.rand(10)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.show( plt.hist(np.random.rand(100)))

In [ ]:
plt.show( plt.hist(np.random.rand(20000)))

In [ ]:
# distribuição normal
plt.show( plt.hist(np.random.randn(1000)))

In [ ]:
plt.show( plt.hist(np.random.randn(10000)))

URL https://raw.githubusercontent.com/vladimiralencar/Alunos-UEPB-TopicosEspeciaisEmBancoDeDados/master/Python-Para-Analise-de-Dados/iris.csv

In [37]:
url = 'https://raw.githubusercontent.com/vladimiralencar/Alunos-UEPB-TopicosEspeciaisEmBancoDeDados/master/Python-Para-Analise-de-Dados/iris.csv'

In [38]:
arq = np.loadtxt(url, delimiter=',', usecols=(0,1,2,3), skiprows=1)
arq

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
arq.dtype

In [ ]:
type(arq)

In [ ]:
arq.shape

In [ ]:
d1, d2 = np.loadtxt(url, delimiter=',', usecols=(0,1), skiprows=1, unpack=True)

In [ ]:
d1[:10]

In [ ]:
plt.show( plt.hist(d1))

In [ ]:
plt.show( plt.hist(d2))

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.show(plt.plot(d1,d2, 'o', markersize=8, alpha=0.75))

# Estatística - Funções

In [ ]:
a = np.array([1,5,7,9,0,-4,7,8,10, 50, 30])
a

In [ ]:
a.shape

In [ ]:
a.dtype

In [ ]:
media = np.mean(a)
media

In [ ]:
desvio_padrao = np.std(a)
desvio_padrao

In [ ]:
plt.show(plt.hist(a))

In [ ]:
variancia = np.var(a)
variancia

In [ ]:
d = np.arange(1,10) # exclusive 
d

In [ ]:
np.sum(d)

In [ ]:
np.prod(d)

In [ ]:
np.cumsum(d)

In [ ]:
# array com 2 colunas - Distribuição Normal
a = np.random.randn(400, 2)
a.shape

In [ ]:
a[:2]

In [ ]:
col0 = a[:, 0]
col0.shape

In [ ]:
col00 = a[0:400, 0]
col00.shape

In [ ]:
m0 = np.mean(col0)
m0

In [ ]:
a[:3]

In [ ]:
col1 = a[:, 1]
col1.shape

In [ ]:
m1 = np.mean(col1)
m1

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.figure(figsize=(12,8))
plt.plot(col0, col1, 'o', markersize=8, alpha=0.75)
plt.show()

In [ ]:
plt.figure(figsize=(12,8))

plt.plot(m0, m1, 'ro', markersize=16)
plt.plot(col0, col1, 'o', markersize=8, alpha=0.75)
plt.show()

In [ ]:
plt.show(plt.hist(col0))

In [ ]:
plt.show(plt.hist(col1))

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
a[:3]

In [ ]:
np.array([-0.26805,  0.22921, 0.72325, -1.16817])

In [ ]:
np.array([-0.26805,  0.22921, 0.72325, -1.16817]) + 100

# Colocar em Escala (Normalização - Média = 0, Desvio padrão = 1)

In [ ]:
(np.array([-0.26805,  0.22921, 0.72325, -1.16817]) - a.mean()) / a.std()

#######################################=======

In [ ]:
np.around([-0.26805,  0.22921, 0.72325, -1.16817])

In [ ]:
c = np.array([-0.26805,  0.22921, 0.72325, -1.16817])
c

In [ ]:
d = c.flatten() # 1 dimensão
d

In [ ]:
# Concatenação de Arrays
w = np.array([5,6])
w

In [ ]:
v = np.array([1,2,3,4])
v

In [ ]:
z = np.concatenate((v,w), axis=0)
z

In [ ]:
# Reshape
a = np.arange(12)
a

In [ ]:
a.shape

In [ ]:
b = a.reshape(3,4)
b

In [ ]:
b = a.reshape(6,2)
b

In [ ]:
b.shape

In [ ]:
b.ndim

In [ ]:
a.ndim