In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
# Medical Cost Personal Datasets
url = 'insurance.csv'
df = pd.read_csv(url)
print(len(df))
df.head()

1338


age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
atributos = list(df.columns)
atributos

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

In [4]:
atributos = ['idade', 'sexo', 'IMC', 'num_filhos', 'fumante', 'regiao', 'valor_seguro']
atributos

['idade', 'sexo', 'IMC', 'num_filhos', 'fumante', 'regiao', 'valor_seguro']

In [5]:
df.columns = atributos
df.head()

idade    sexo     IMC  num_filhos fumante     regiao  valor_seguro
0     19  female  27.900           0     yes  southwest   16884.92400
1     18    male  33.770           1      no  southeast    1725.55230
2     28    male  33.000           3      no  southeast    4449.46200
3     33    male  22.705           0      no  northwest   21984.47061
4     32    male  28.880           0      no  northwest    3866.85520

In [6]:
df['sexo'] = df.sexo.apply(lambda x : 'Masculino' if x == 'male' else 'Feminino')
df.head()

idade       sexo     IMC  num_filhos fumante     regiao  valor_seguro
0     19   Feminino  27.900           0     yes  southwest   16884.92400
1     18  Masculino  33.770           1      no  southeast    1725.55230
2     28  Masculino  33.000           3      no  southeast    4449.46200
3     33  Masculino  22.705           0      no  northwest   21984.47061
4     32  Masculino  28.880           0      no  northwest    3866.85520

In [7]:
df['fumante'] = df.fumante.apply(lambda x : 'sim' if x == 'yes' else 'nao')
df.head()

idade       sexo     IMC  num_filhos fumante     regiao  valor_seguro
0     19   Feminino  27.900           0     sim  southwest   16884.92400
1     18  Masculino  33.770           1     nao  southeast    1725.55230
2     28  Masculino  33.000           3     nao  southeast    4449.46200
3     33  Masculino  22.705           0     nao  northwest   21984.47061
4     32  Masculino  28.880           0     nao  northwest    3866.85520

In [8]:
regioes = {'southwest': 'sul', 'southeast': 'sudeste', 'northwest': 'Norte', 'northeast': 'Nordeste'}
regioes

{'southwest': 'sul',
 'southeast': 'sudeste',
 'northwest': 'Norte',
 'northeast': 'Nordeste'}

In [9]:
df['regiao'] = df.regiao.map(regioes)
df.head()

idade       sexo     IMC  num_filhos fumante   regiao  valor_seguro
0     19   Feminino  27.900           0     sim      sul   16884.92400
1     18  Masculino  33.770           1     nao  sudeste    1725.55230
2     28  Masculino  33.000           3     nao  sudeste    4449.46200
3     33  Masculino  22.705           0     nao    Norte   21984.47061
4     32  Masculino  28.880           0     nao    Norte    3866.85520

In [10]:
df.to_csv('seguros.csv', index=False)
!ls -lah 

total 360
drwxr-xr-x     6 valencar  staff   192B May 28 10:14 .
drwx------@ 1071 valencar  staff    33K May 28 10:09 ..
drwxr-xr-x     3 valencar  staff    96B May 28 10:12 .ipynb_checkpoints
-rw-r--r--@    1 valencar  staff    54K May 28 10:09 insurance.csv
-rw-r--r--@    1 valencar  staff    65K May 28 10:12 previsao_seguros.ipynb
-rw-r--r--     1 valencar  staff    55K May 28 10:14 seguros.csv


# Transformacão de Dados

In [11]:
dict_categorias = {}

dict_categorias['sexo'] = {
        'Feminino': 0,
        'Masculino': 1
}
dict_categorias

{'sexo': {'Feminino': 0, 'Masculino': 1}}

In [12]:
dict_categorias['sexo']

{'Feminino': 0, 'Masculino': 1}

In [13]:
dict_categorias['sexo']['Masculino']

1

In [14]:
df['sexo'] = df.sexo.map(dict_categorias['sexo'])
df.head()

idade  sexo     IMC  num_filhos fumante   regiao  valor_seguro
0     19     0  27.900           0     sim      sul   16884.92400
1     18     1  33.770           1     nao  sudeste    1725.55230
2     28     1  33.000           3     nao  sudeste    4449.46200
3     33     1  22.705           0     nao    Norte   21984.47061
4     32     1  28.880           0     nao    Norte    3866.85520

In [15]:
dict_categorias['fumante'] = {
        'nao': 0,
        'sim': 1
}
dict_categorias

{'sexo': {'Feminino': 0, 'Masculino': 1}, 'fumante': {'nao': 0, 'sim': 1}}

In [16]:
df['fumante'] = df.fumante.map(dict_categorias['fumante'])
df.head()

idade  sexo     IMC  num_filhos  fumante   regiao  valor_seguro
0     19     0  27.900           0        1      sul   16884.92400
1     18     1  33.770           1        0  sudeste    1725.55230
2     28     1  33.000           3        0  sudeste    4449.46200
3     33     1  22.705           0        0    Norte   21984.47061
4     32     1  28.880           0        0    Norte    3866.85520

In [17]:
df.regiao.unique()

array(['sul', 'sudeste', 'Norte', 'Nordeste'], dtype=object)

In [18]:
dict_categorias['regiao'] = {
        'sul' : 0, 
        'sudeste': 1, 
        'Norte': 2, 
        'Nordeste': 3
}
dict_categorias

{'sexo': {'Feminino': 0, 'Masculino': 1},
 'fumante': {'nao': 0, 'sim': 1},
 'regiao': {'sul': 0, 'sudeste': 1, 'Norte': 2, 'Nordeste': 3}}

In [19]:
df['regiao'] = df.regiao.map(dict_categorias['regiao'])
df.head()

idade  sexo     IMC  num_filhos  fumante  regiao  valor_seguro
0     19     0  27.900           0        1       0   16884.92400
1     18     1  33.770           1        0       1    1725.55230
2     28     1  33.000           3        0       1    4449.46200
3     33     1  22.705           0        0       2   21984.47061
4     32     1  28.880           0        0       2    3866.85520

# construção do modelo

In [20]:
from sklearn import linear_model
modelo = linear_model.LinearRegression()

In [21]:
len(df)

1338

In [ ]:
# X e y

In [22]:
X = df[ ['idade', 'sexo', 'IMC', 'num_filhos', 'fumante', 'regiao'] ]
X.head()

idade  sexo     IMC  num_filhos  fumante  regiao
0     19     0  27.900           0        1       0
1     18     1  33.770           1        0       1
2     28     1  33.000           3        0       1
3     33     1  22.705           0        0       2
4     32     1  28.880           0        0       2

In [23]:
y = df['valor_seguro']
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: valor_seguro, dtype: float64

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
len(X_train), len(X_test)

(936, 402)

In [25]:
# converte em matrizes

In [26]:
X_train_mat = X_train.to_numpy()
X_train_mat

array([[61.   ,  0.   , 31.16 ,  0.   ,  0.   ,  2.   ],
       [46.   ,  1.   , 27.6  ,  0.   ,  0.   ,  0.   ],
       [54.   ,  0.   , 31.9  ,  3.   ,  0.   ,  1.   ],
       ...,
       [58.   ,  1.   , 25.175,  0.   ,  0.   ,  3.   ],
       [37.   ,  0.   , 47.6  ,  2.   ,  1.   ,  0.   ],
       [55.   ,  1.   , 29.9  ,  0.   ,  0.   ,  0.   ]])

In [27]:
y_train_mat = y_train.to_numpy()
y_train_mat[:10]

array([13429.0354 , 24603.04837, 27322.73386, 42303.69215, 42112.2356 ,
       41676.0811 ,  4562.8421 ,  3490.5491 , 12485.8009 ,  6748.5912 ])

In [28]:
# Fit do modelo

In [29]:
modelo.fit(X_train_mat, y_train_mat)

LinearRegression()

In [ ]:
# Avaliacao do modelo

In [30]:
y_test_pred = modelo.predict(X_test.to_numpy() )
y_test_pred[:10]

array([ 8931.42116433,  7070.90670308, 36937.08049605,  9596.99214428,
       27008.35487143, 10866.48485361,    37.46102168, 17222.80920435,
         918.30811536, 11396.55374009])

In [31]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test.to_numpy(), y_test_pred)

33805466.898688614

In [32]:
from sklearn.metrics import r2_score

r2_score(y_test.to_numpy(), y_test_pred)

0.7694415927057693

In [ ]:
# Deploy

In [33]:
import pickle 

with open('modelo.pkl', 'wb') as f:
    pickle.dump(modelo, f)
    
with open('dict_categorias.pkl', 'wb') as f:
    pickle.dump(dict_categorias, f)
        
with open('modelo.pkl', 'rb') as f:
    loaded_model = pickle.load(f)
    
print(loaded_model)

LinearRegression()


In [34]:
y_test_pred = loaded_model.predict(X_test.to_numpy() )
print(mean_squared_error(y_test.to_numpy(), y_test_pred))
print(r2_score(y_test.to_numpy(), y_test_pred))

33805466.898688614
0.7694415927057693


In [35]:
#	idade	sexo	IMC	    num_filhos	fumante	regiao	 valor_seguro
# 32	      1	   28.880	0	         0	      2	     3866.85520
x1 = np.array([35,     1,   28.880, 0,        0,     2 ])
modelo.predict(x1.reshape(1, -1))[0]

6526.147102241623

In [ ]:
===

In [36]:
df.columns

Index(['idade', 'sexo', 'IMC', 'num_filhos', 'fumante', 'regiao',
       'valor_seguro'],
      dtype='object')

In [37]:
df.head()

idade  sexo     IMC  num_filhos  fumante  regiao  valor_seguro
0     19     0  27.900           0        1       0   16884.92400
1     18     1  33.770           1        0       1    1725.55230
2     28     1  33.000           3        0       1    4449.46200
3     33     1  22.705           0        0       2   21984.47061
4     32     1  28.880           0        0       2    3866.85520

In [ ]:
#	idade	sexo	IMC	    num_filhos	fumante	regiao	 valor_seguro
# 32	      1	   28.880	0	         0	      2	     3866.85520
x1 = np.array([35,     1,   28.880, 0,        0,     2 ])
modelo.predict(x1.reshape(1, -1))[0]

In [38]:
dict_categorias

{'sexo': {'Feminino': 0, 'Masculino': 1},
 'fumante': {'nao': 0, 'sim': 1},
 'regiao': {'sul': 0, 'sudeste': 1, 'Norte': 2, 'Nordeste': 3}}

In [39]:
!ls -lah

total 328
drwxr-xr-x     8 valencar  staff   256B May 28 10:15 .
drwx------@ 1071 valencar  staff    33K May 28 10:09 ..
drwxr-xr-x     3 valencar  staff    96B May 28 10:12 .ipynb_checkpoints
-rw-r--r--     1 valencar  staff   140B May 28 10:15 dict_categorias.pkl
-rw-r--r--@    1 valencar  staff    54K May 28 10:09 insurance.csv
-rw-r--r--     1 valencar  staff   499B May 28 10:15 modelo.pkl
-rw-r--r--@    1 valencar  staff    41K May 28 10:14 previsao_seguros.ipynb
-rw-r--r--     1 valencar  staff    55K May 28 10:14 seguros.csv


In [ ]:
# from sklearn import preprocessing
# sexo = preprocessing.LabelEncoder()
# sexo.fit(['Masculino', 'Feminino', 'Masculino'])
# print(sexo.classes_)
# print(sexo.transform(['Masculino', 'Feminino', 'Masculino']))
# print(sexo.inverse_transform([0, 0, 1, 0, 1]))



In [ ]:
# sexo , mapping_index = pd.Series(df.sexo).factorize()
# sexo
# mapping_index[0]